export const Images= {
    waive: require('./waive-black.webp'),
    bell:  require('./bell.webp'),
    bolt: require('./bolt.webp'),
    celebrate:  require('./celebrate.webp'),
    coffee: require('./coffee.webp'),
    LogoImage:  require('./zeamani.svg'),
    jellyfish: require('./jellyfish.webp'),
    gradHat:  require('./grad-hat.webp'),
    light: require('./light.webp'),
    meltingFace:  require('./melting-face.webp'),
    please: require('./please.webp'),
    test:require('./test.svg'),
    og:require('./og.png'),
    grid:require('./grid.svg'),
    csharp:require('./c.svg'),
    java:require('./java.svg'),
    php:require('./php.svg'),
    postgresql:require('./postgresql.svg'),
    tensorflow:require('./tensorflow.svg'),
    react:require('./react.svg'),
    python:require('./python.svg'),
    dataNotFound:require('./data-not-found.svg')
    
}