
import "fireup/styles/globals.css";
import { Toaster } from 'react-hot-toast';


import { headers } from "next/headers";

import { TRPCReactProvider } from "fireup/trpc/react";
import Footer from "fireup/app/_components/shared/footer/Footer";
import Navbar from "fireup/app/_components/shared/navbar/Navbar";
import { opensans, pacifico, roboto } from "fireup/styles/Fonts";
import { SessionProvider } from "next-auth/react";
import SessionProvide from "fireup/app/_components/auth/sessionProvide";
import Image from "next/image";
import { Images } from "fireup/app/resources";
//analytics
import { Analytics } from '@vercel/analytics/react';
import Loglib from "@loglib/tracker/react";
import ClientLayout from "../_components/shared/layout/ClientLayouts";
import {Ubuntu} from "next/font/google"
import { cn } from "fireup/lib/utils";


export const metadata = {
  title: "zeamani",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const ubuntu = Ubuntu({
  subsets: ['latin'], // Specify the subsets you want (e.g., 'latin', 'latin-ext')
  weight: ['400', '500', '700'], // Specify the font weights you need
  variable: '--font-ubuntu', // Optional: Set a CSS variable to use with custom styles
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(ubuntu.className,"font-extralight  overflow-x-hidden")}>
        <TRPCReactProvider headers={headers()}>
        {/* <div className={`fixed w-full h-full top-0 bg-opacity-20 invert bg-[url(https://d2vwwcvoksz7ty.cloudfront.net/grid.svg)] z-0`}></div> */}
         <div className="blob"></div>
        
        <Toaster/>
        
          {children}
       
         
         <Loglib
                config={{
                    id: "zeamani",
                }}
            />
          <Analytics/>
          </TRPCReactProvider>

      </body>
    </html>
  );
}
